name: Deploy to AWS EC2

on:
  push:
    branches:
      -  master  # Trigger only when code is pushed to the  master branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the latest code
    - name: Checkout repository
      uses: actions/checkout@v3

    # Step 2: Setup SSH
    - name: Setup SSH
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" | base64 --decode > ec2-key.pem
        chmod 600 ec2-key.pem
        ssh-keyscan -t rsa ${{ secrets.EC2_IP }} >> ~/.ssh/known_hosts

    # Step 3: Copy project to EC2
    - name: Copy files to EC2 server
      run: |
        scp -i ec2-key.pem -o StrictHostKeyChecking=no -r . ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }}:/home/${{ secrets.EC2_USER }}

    # Step 4: SSH into the EC2 server and run deployment commands
    - name: Run deployment commands on EC2
      run: |
        ssh -i ec2-key.pem -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          cd /home/${{ secrets.EC2_USER }}
          python3 -m venv venv || true
          source venv/bin/activate
          pip install -r requirements.txt
          python manage.py migrate
          python manage.py collectstatic --noinput
          systemctl restart gunicorn || true
        EOF
